Update shellweb

diff --git a/shellweb b/shellweb
--- a/shellweb
+++ b/shellweb
@@ -15,26 +15,24 @@ else
 fi
 
 usage() {
-	echo "usage: ${0##*/} [-v] [-a authfile] [-d rootdir] [-p port] [-r uri]" >&2
+	echo "usage: ${0##*/} [-v] [-a authfile] [-d rootdir] [-p port] [-r proxy_spec]" >&2
 	exit 1
 }
 
-while getopts "a:d:p:vr:" OPT; do case $OPT in
-	a)      authfile=$OPTARG; auth_enabled=true;;
+while getopts "a:d:p:r:v" OPT; do case $OPT in
+	a)      auth_file=$OPTARG; auth_enabled=true;;
 	d)      root=$OPTARG;;
 	p)      port=$OPTARG;;
 	v)      verbose=true;;
-	r)	uri=$OPTARG; proxy_mode=true;;
+	r)	proxy_spec=$OPTARG; proxy_mode=true;;
 	*)      usage;;
 esac; done
 shift $((OPTIND - 1))
 
-if [ -n "$authfile" ]; then
-	authfile=$(readlink -f -- "$authfile")
-	if ! [ -r "$authfile" -a -f "$authfile" ]; then
-		echo "could not read file '$authfile'" >&2
-		exit 1
-	fi	
+authfile=$(readlink -f -- "$authfile")
+if ! [ -r "$authfile" -a -f "$authfile" ]; then
+	echo "could not read file '$authfile'" >&2
+	exit 1
 fi
 
 $verbose && echo "root directory is $root" >&2
@@ -55,7 +53,7 @@ authenticate() {
 			$verbose && echo "logged in as $user" >&2
 			return 0
 		fi
-	done < "$authfile"
+	done < "$auth_file"
 	false
 }
 
@@ -295,20 +293,20 @@ EOF
 }
 
 proxy() {
-	uri_port=${uri##*:}
-	if [[ x"$uri_port" = x"$uri" ]]; then
-		uri_port=80
+	proxy_port=${proxy_spec##*:}
+	if [[ x"$proxy_port" = x"$proxy_spec" ]]; then
+		proxy_port=80
 	fi
-	while read -p v; do
+	while read -p -r v; do
 		if [[ $v = "Host: "* ]]; then
-			printf "Host: ${uri}\r\n"
+			printf "Host: ${proxy_spec}\r\n"
 		elif [[ $v = $(printf "\r\n") ]]; then
 			ip=$(fstat -p $ncpid | awk '$7 == "tcp" {print $11}' | sed '/^$/d')
 			printf "X-Forwarded-For: ${ip}\r\n\r\n"
 		else
 			printf "$v\n"
 		fi
-	done | nc ${uri%%:*} $uri_port >&p
+	done | nc ${proxy_spec%%:*} $proxy_port >&p
 }
 			
 
